# --- !Ups

ALTER TABLE restaurants
ADD COLUMN IF NOT EXISTS email VARCHAR(255),
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS city VARCHAR(255),
ADD COLUMN IF NOT EXISTS state VARCHAR(255),
ADD COLUMN IF NOT EXISTS zip VARCHAR(255),
ADD COLUMN IF NOT EXISTS phone VARCHAR(255);


# --- !Downs

ALTER TABLE restaurants
DROP COLUMN IF EXISTS email,
DROP COLUMN IF EXISTS address,
DROP COLUMN IF EXISTS city,
DROP COLUMN IF EXISTS state,
DROP COLUMN IF EXISTS zip,
DROP COLUMN IF EXISTS phone;